chameleon-system/chameleon-shop

.github/PULL_REQUEST_TEMPLATE.md

| Branch?       | 6.2.x
| BC breaks?    | no 
| Fixed issues  | 

Improve branch name in pull request template

---

composer.json

| Branch?       | 6.2.x
| Fixed issues  | 
Remove the ESONO packagist entry (isn't interesting for everyone else).

Remove ESONO packagist

---

src/SearchBundle/objects/db/TShopSearchIndexer.class.php

| Fixed issues  | chameleon-system/chameleon-system#33

ref #33: Set correct log level for indexing completion message

---

src/ShopArticleReviewBundle/Resources/translations/admin-enum.de.xliff
src/ShopArticleReviewBundle/Resources/translations/messages.de.xliff
src/ShopArticleReviewBundle/Resources/translations/messages.en.xliff
src/ShopBundle/Resources/translations/admin.de.xliff
src/ShopBundle/Resources/translations/admin.en.xliff
src/ShopBundle/Resources/translations/messages.de.xliff
src/ShopBundle/Resources/translations/messages.en.xliff
src/ShopBundle/objects/TCMSListManager/TCMSListManagerShopArticles.php
src/ShopBundle/objects/TShopBasket/TShopBasketCore.class.php
src/ShopOrderStatusBundle/Resources/translations/messages.de.xliff
src/ShopOrderStatusBundle/Resources/translations/messages.en.xliff
src/ShopPaymentTransactionBundle/Resources/translations/admin.de.xliff
src/ShopPaymentTransactionBundle/Resources/translations/admin.en.xliff

| Fixed issues  | chameleon-system/chameleon-system#79

ref #79: Fix typos

---

src/ShopProductExportBundle/Modules/ShopProductExportModule.php

| Fixed issues  | chameleon-system/chameleon-system#129

ref #129: Return on error to avoid generating exports without permission

---

src/ShopPaymentTransactionBundle/objects/TCMSTableEditor/TPkgShopPaymentTransaction_TCMSTableEditorShopOrder.class.php

| BC breaks?    | no 
| Fixed issues  | chameleon-system/chameleon-system#166

ref #166 : correct payment transaction redirect url

---

src/ShopArticleDetailPagingBundle/Bridge/Service/ContentFromUrlLoaderStandardService.php

| Fixed issues  | chameleon-system/chameleon-system#175

ref #175: Also use user agent for paging data request

---

src/ShopBundle/objects/TCMSSmartURLHandler/TPkgShopRouteControllerArticle.class.php

| Fixed issues  | chameleon-system/chameleon-system#181

181 handle deactivated article correctly

---

README.md

Extend information in README

---

src/ShopBundle/objects/TShopBasket/TShopBasketArticleCoreList.class.php

| Fixed issues  | chameleon-system/chameleon-system#236

ref #236: correct total value on percentage discounts

---

UPGRADE-6.3.md
src/ShopCurrencyBundle/pkgShop/objects/db/TPkgShopCurrency_ShopDiscount.class.php
src/ShopCurrencyBundle/pkgShop/objects/db/TPkgShopCurrency_ShopPaymentMethod.class.php
src/ShopCurrencyBundle/pkgShop/objects/db/TPkgShopCurrency_ShopShippingType.class.php

| Deprecations? | yes
| Fixed issues  | chameleon-system/chameleon-system#243

ref #243: deprecate unused classes

---

src/ShopPaymentTransactionBundle/objects/TPkgShopPaymentTransactionManagerEndPoint.class.php

| Fixed issues  | chameleon-system/chameleon-system#208

ref #208: Fix variable name

---

src/ShopCurrencyBundle/Bridge/Chameleon/Migration/Script/update-1545232400.inc.php

| Branch        | 6.2.x 
| Fixed issues  | chameleon-system/chameleon-system#234

ref #234: add update to add currency voucher fields

---

src/ShopCurrencyBundle/pkgShop/objects/db/TPkgShopCurrency_ShopVoucher.class.php

| Branch        |  6.2.x
| Fixed issues  | chameleon-system/chameleon-system#270

ref #270: round voucher values in used up check

---

UPGRADE-6.3.md
src/ShopBundle/objects/db/TShopArticleReview.class.php

| BC breaks?    | no (probably not, documented)
| Fixed issues  | chameleon-system/chameleon-system#70
The behavior of TShopArticleReview was changed to white-list.

70 guard table fields closely

---

src/ShopBundle/Resources/BackendPageDefs/articlesearchindex.pagedef.php
src/ShopBundle/Resources/BackendPageDefs/cmsShopStatistic.pagedef.php

| Fixed issues  | chameleon-system/chameleon-system#100
https://github.com/chameleon-system/chameleon-base/pull/159/files must be merged before this PR.

ref #100: Add sidebar module to pagedefs

---

src/ShopBundle/objects/BackendModules/MTShopStatistic/views/standard.view.php

| Branch        |features
| BC breaks?    | no  
| Fixed issues  | chameleon-system/chameleon-system#297
statistic styling

ref #297: statistics styling

---

src/ShopBundle/Resources/translations/admin.de.xliff
src/ShopBundle/Resources/translations/admin.en.xliff
src/ShopBundle/objects/BackendModules/CMSShopArticleIndex/views/standard.view.php

| BC breaks?    | no  
| Fixed issues  | chameleon-system/chameleon-system#299
article search index: styling

ref #299: article search index: styling

---

src/ShopBundle/objects/TCMSTableEditor/TCMSShopTableEditor_ShopVoucherSeries.class.php
src/ShopBundle/objects/TCMSTableEditor/TCMSTableEditorShopOrderEndPoint.class.php
src/ShopPaymentIPNBundle/objects/TCMSTableEditor/TPkgShopPaymentIPN_TCMSTableEditor_PkgShopPaymentIpnMessage.class.php
src/ShopPaymentTransactionBundle/objects/TCMSTableEditor/TPkgShopPaymentTransaction_TCMSTableEditorShopOrder.class.php

| Fixed issues  | chameleon-system/chameleon-system#99

ref #99: replace icons with fontawesome classes

---

src/ShopBundle/objects/TCMSListManager/TCMSListManagerShopArticles.php

| Branch        | master 
| BC breaks?    | no  
| Fixed issues  | chameleon-system/chameleon-system#256

ref #256: add submitOnSelect for table selections

---

src/ShopBundle/objects/TCMSSmartURLHandler/TCMSSmartURLHandler_BuyProductDirectLink.class.php
src/ShopBundle/objects/TCMSSmartURLHandler/TCMSSmartURLHandler_ShopBasketSteps.class.php
src/ShopBundle/objects/TCMSSmartURLHandler/TCMSSmartURLHandler_ShopIPayment.class.php
src/ShopCurrencyBundle/Service/ShopCurrencyService.php
src/ShopProductExportBundle/ShopProductExporter.php
src/ShopProductExportBundle/objects/TPkgShopProductExportBaseEndPoint.class.php
src/ShopRatingServiceBundle/objects/db/TPkgShopRatingServiceRating.class.php

| Fixed issues  | chameleon-system/chameleon-system#323

ref #323: Remove deprecated code usages

---

src/ShopBundle/objects/db/TShopModuleArticleListFilter/TShopModuleArticleListFilter.class.php

| Fixed issues  | chameleon-system/chameleon-system#396

ref #396: Handle null value to avoid warnings

---

src/ShopBundle/objects/TCMSSmartURLHandler/TPkgShopRouteControllerArticle.class.php

| Branch        |6.2.x
| Fixed issues  | chameleon-system/chameleon-system#112

ref #112: Handle category empty case like other cannot show case

---

src/ShopBundle/objects/db/TShopPaymentHandler/TShopPaymentHandlerDebit.class.php

| Fixed issues  | chameleon-system/chameleon-system#443

ref #443: Use validate() instead of validateValue()

---

src/ShopBundle/objects/TCMSSmartURLHandler/TPkgShopRouteControllerArticle.class.php
src/ShopBundle/objects/db/TShopCategory.class.php

| BC breaks?    | no - possible: A public method now returns correct values
| Fixed issues  | chameleon-system/chameleon-system#457

ref #457: Correct return value of AllowDisplayInShop(); fix follow-up bugs (route controller)

---

src/ShopBundle/mappers/social/TPkgShopMapper_SocialSharePrivacy.php
src/ShopBundle/objects/WebModules/MTShopPageMetaCore/MTShopPageMetaCore.class.php

| Deprecations? | yes
| Fixed issues  | chameleon-system/chameleon-system#461

461 share image metadata

---

src/ShopBundle/mappers/social/TPkgShopMapper_SocialSharePrivacy.php
src/ShopBundle/objects/WebModules/MTShopPageMetaCore/MTShopPageMetaCore.class.php

| Fixed issues  | chameleon-system/chameleon-system#461

461 share image metadata 62

---

src/ShopBundle/Resources/views/snippets-cms/TCMSFieldShopVariantDetails/main-product.html.twig

| Branch        | features / 6.2.3
| Fixed issues  | chameleon-system/chameleon-system#441

ref #441: align content with label

---

src/ShopCurrencyBundle/views/TCMSFields/TPkgShopCurrency_CMSFieldPrice/postload.view.php

| Fixed issues  | chameleon-system/chameleon-system#413

ref #413 always set formatted currency price field

---

src/ShopBundle/Interfaces/ProductVariantServiceInterface.php
src/ShopBundle/Resources/config/services.xml
src/ShopBundle/Service/ProductVariantService.php
src/ShopBundle/mappers/article/TPkgShopMapper_ArticleGetOneVariantType.class.php
src/ShopBundle/objects/TCMSSmartURLHandler/TPkgShopRouteControllerArticle.class.php
src/ShopBundle/objects/WebModules/MTShopArticleDetails.class.php
src/ShopBundle/objects/db/TShop.class.php
src/ShopBundle/objects/db/TShopArticle.class.php
src/ShopBundle/objects/db/TShopVariantDisplayHandler/TShopVariantDisplayHandler.class.php

| Deprecations? | yes
| Fixed issues  | chameleon-system/chameleon-system#501

501 proper variant selection

---

src/ShopBundle/Service/ProductVariantService.php

| Fixed issues  | chameleon-system/chameleon-system#501

ref #501: Do not destroy list

---

src/ShopBundle/objects/db/TShopPaymentHandler/TShopPaymentHandlerPayPal_PayViaLink.class.php

| Fixed issues  | chameleon-system/chameleon-system#523

523 proper info reporting

---

src/ShopBundle/objects/db/TShopArticle.class.php

| New feature?  | 
| Fixed issues  | chameleon-system/chameleon-system#532

ref #532: Trigger parent cache

---

src/ShopBundle/objects/TCMSTableEditor/TCMSShopTableEditor_ShopVoucherSeries.class.php

| Fixed issues  | chameleon-system/chameleon-system#541

ref #541: Avoid problems with unescaped quotes

---

src/ShopBundle/objects/TShopBasket/TShopBasketCore.class.php

ref #540: Add special method for none-sponsored vouchers

---

src/SearchBundle/objects/db/TShopSearchIndexer.class.php
src/ShopBundle/objects/CronJobs/TCMSCronJob_ShopSearchIndex.class.php
src/ShopBundle/objects/TCMSTableEditor/TCMSShopTableEditor_ShopVoucherSeries.class.php
src/ShopProductExportBundle/objects/TPkgShopProductExportBaseEndPoint.class.php

| Fixed issues  | chameleon-system/chameleon-system#563

ref #563: Replace usages of old cache's enable methods

---

src/ShopBundle/Resources/views/snippets-cms/TCMSFieldShopVariantDetails/main-product.html.twig

| Fixed issues  | chameleon-system/chameleon-system#580

ref #580: Show popup correctly and react on checkbox click correctly

---

src/ShopBundle/objects/WebModules/MTShopBasketCore/MTShopBasketCoreEndpoint.class.php

| Fixed issues  | chameleon-system/chameleon-system#581

ref #581: transfer custom data to new basket article

---

src/ShopBundle/objects/TShopBasket/TShopBasketCore.class.php

This reverts commit 0af5a89f
| Bug fix?      | no - sort of: removes a new bug

Revert "ref #540: Add special method for none-sponsored vouchers"

---

src/ShopBundle/objects/TShopBasket/TShopBasketCore.class.php
src/ShopBundle/objects/TShopBasket/TShopBasketVoucherCoreList.class.php

| Tests pass?   | yes  
This fixes yet another edgecase. In fact, it fixes the original edgecase described in the issue as we were finally able to reproduce it.

mark vouchers as valid from outside the list

---

src/ShopBundle/objects/TCMSListManager/TCMSListManagerShopArticles.php

| Fixed issues  | chameleon-system/chameleon-system#587

587 store table obj correctly

---

composer.json
src/AmazonPaymentBundle/Resources/config/services.xml
src/ShopBundle/Resources/config/logging.xml
src/ShopBundle/Resources/config/mappers.xml
src/ShopBundle/Resources/config/services.xml
src/ShopCurrencyBundle/Resources/config/services.xml
src/ShopRatingServiceBundle/Resources/config/services.xml

| BC breaks?    | yes
| Tests pass?   | yes  
| Fixed issues  | -
Upgrade to Symfony 4.4
Projects that update to this version might need to make those services explicitly public that are being fetched from the container at runtime via the service locator.

Symfony44 upgrade

---

src/ShopBundle/objects/TShopBasket/TShopBasketArticleCoreList.class.php
src/ShopBundle/objects/TShopBasket/TShopBasketCore.class.php
src/ShopBundle/objects/WebModules/MTShopBasketCore/MTShopBasketCoreEndpoint.class.php

| Fixed issues  | chameleon-system/chameleon-system#650

ref #650: merge basket items with identical basket item data

---

src/ShopBundle/Resources/config/services.xml

fixes #700
| Fixed issues  | chameleon-system/chameleon-system#700   

tag search suggest controller

---

src/AmazonPaymentBundle/Tests/config.yml

| Fixed issues  | chameleon-system/chameleon-system#693   

make testpdo public as it is fetched from locator

---

src/ShopBundle/objects/db/TShopOrderStep/TShopStepUserDataV2EndPoint.class.php

| Fixed issues  | chameleon-system/chameleon-system#681

681 allow guest checkout again

---

src/ShopBundle/Bridge/Chameleon/Migration/Script/update-1629872884.inc.php

| Fixed issues  | chameleon-system/chameleon-system#584

ref #584: Adapt voucher message

---

src/ShopBundle/Resources/config/services.xml

| Fixed issues  | chameleon-system/chameleon-system#731

ref #731: Payment config loader tagged with public tag

---

src/ShopBundle/Bridge/Chameleon/Migration/Script/update-1629872884.inc.php
src/ShopBundle/Bridge/Chameleon/Migration/Script/update-1629872885.inc.php

| Fixed issues  | chameleon-system/chameleon-system#584

ref #584: Execute message update for all messages (in multiple portals)

---

src/ShopListFilterBundle/mappers/filter/TPkgShopListfilterMapper_FilterNumericSlider.class.php

| Fixed issues  | chameleon-system/chameleon-system#398

ref #398: Adapt step size again

---

src/ShopBundle/objects/TShopBasket/TShopBasketArticleCoreList.class.php
src/ShopBundle/objects/TShopBasket/TShopBasketArticleDiscountCoreList.class.php
src/ShopBundle/objects/TShopBasket/TShopBasketCore.class.php
src/ShopBundle/objects/TShopBasket/TShopBasketDiscountCoreList.class.php
src/ShopBundle/objects/TShopBasket/TShopBasketVoucherCoreList.class.php

| Fixed issues  | chameleon-system/chameleon-system#722   
Fixes a couple of type annotations, all within docblocks so IDEs and static analyzers can properly interpret the types.

ref #722: Correct type annotations

---

src/ShopBundle/Resources/config/services.xml
src/ShopBundle/Service/OrderStepPageService.php
src/ShopBundle/objects/TCMSSmartURLHandler/TPkgShopBasketStepsRouteCollectionGenerator.php

| BC breaks?    | no  
| Fixed issues  | chameleon-system/chameleon-system#774
We reduce the checkout first step route with `/`

ref #774: first checkout step route reduced

---

src/ShopBundle/Resources/translations/admin.de.xliff
src/ShopBundle/Resources/translations/admin.en.xliff
src/ShopBundle/objects/TCMSTableEditor/TCMSTableEditorShopOrderEndPoint.class.php

| Fixed issues  | chameleon-system/chameleon-system#660

ref #660: Add function to (re) call the Wawi export

---

src/ShopBundle/Resources/config/cronjobs.xml
src/ShopBundle/objects/CronJobs/TCMSCronJob_ShopSendOrderNotifications.class.php

| Fixed issues  | chameleon-system/chameleon-system#720

720 send order email language

---

src/ShopBundle/mappers/order/TPkgShopMapper_OrderArticleListSummary.class.php
src/ShopBundle/objects/db/TShopArticle.class.php
src/ShopBundle/objects/db/TShopPaymentHandler/TShopPaymentHandlerIPaymentEndPoint.class.php
src/ShopBundle/objects/db/TShopPaymentHandler/TShopPaymentHandlerPayOne.class.php

| Tests pass?   | no
| Fixed issues  | chameleon-system/chameleon-system#790

790 mandatory before optional

---

src/ShopBundle/objects/db/TShopShippingGroupList.class.php

| Fixed issues  | chameleon-system/chameleon-system#784

ref #784: Check for basket (there is none if no session)

---

src/ShopBundle/mappers/order/TPkgShopMapper_OrderUserData.class.php

| Fixed issues  | chameleon-system/chameleon-system#799

ref #799: add company to address mapping

---

src/ShopBundle/objects/TShopBasket/TShopBasketCore.class.php

| Fixed issues  | chameleon-system/chameleon-system#804

ref #804: prevent the basket validation if an active order is available

---

src/ShopBundle/objects/ArticleList/DatabaseAccessLayer/SortType.php

| Branch        |  7.1.x
| Fixed issues  | chameleon-system/chameleon-system#797

797 remove static call

---

src/ShopBundle/objects/WebModules/MTShopOrderHistory.class.php

| Fixed issues  | chameleon-system/chameleon-system#799

ref #799: add company to address in order history module

---

src/SearchBundle/Bridge/ShopSearchSessionChameleonBridge.php
src/SearchBundle/Resources/config/services.xml

| BC breaks?    | yes
| Fixed issues  | chameleon-system/chameleon-system#823

823 refactor shop search session service to get session from request

---

src/ShopBundle/Bridge/Chameleon/Migration/Script/update-1688558158.inc.php

| Fixed issues  | chameleon-system/chameleon-system#822

ref 822: fix index for class field in shop_order_step
