src/ShopBundle/EventListener/UpdateVariantParentStockListener.php, src/ShopBundle/objects/TCMSTableEditor/TCMSShopTableEditor_ShopArticle.class.php, src/ShopBundle/objects/db/TShopArticle.class.php
| Fixed issues  | chameleon-system/chameleon-system#83
Two errors fixed when saving the variant product with a stock change: 
- Activation of a variant product (based on the stock)
- "Parent variant active" flag corrected for the main product
=> 83 product variant activation 2

src/ShopBundle/Resources/config/mappers.xml, src/ShopBundle/objects/WebModules/ViewMyOrderDetails/MTShopViewMyOrderDetails.php
| Fixed issues  | chameleon-system/chameleon-system#133
There were actually 2 problems introduced in 6.2.0:
- The new service ID for the mapper was set in DB, but not defined.
- MTShopViewMyOrderDetails::$orderIdRequested was never declared, but written in MTShopViewMyOrderDetails::Init(). This was a bit unclean in previous versions, but breaks since 6.2.0 as we no longer allow magic setter in modules.
=> ref #133: Add missing things to make order printing work again

src/ShopBundle/objects/TCMSSmartURLHandler/TPkgShopRouteControllerArticle.class.php, src/ShopBundle/objects/db/TShopCategory.class.php
| BC breaks?    | no   
| Tests pass?   | yes   
| Fixed issues  | chameleon-system/chameleon-system#195
Before caching the category response, we now check for access rights every time. This way the access right is not being cached independently of the user.
The impact on performance by this additional check is reasonable. We tested this using blackfire as a profiler on a page with 789 categories.
=> ref #195: check access rights before cache

src/ImageHotspotBundle/mappers/TPkgImageHotspotMapper.class.php, src/ShopBundle/Bridge/Chameleon/Migration/Script/update-1546853355.inc.php
…pot mapper
| Branch        |  master
| Fixed issues  | chameleon-system/chameleon-system#260
Adding an image crop field for image hotspots in preparation for https://github.com/chameleon-system/chameleon-shop-theme-bundle/issues/16
ATTENTION: This PR requires the ImageCropBundle to be integrated in chameleon-base.
=> 260 image hotspots create image crop field and map it

src/ShopBundle/Bridge/Chameleon/Migration/Script/update-1552666351.inc.php
| Fixed issues  | chameleon-system/chameleon-shop-theme-bundle#16
chameleon-system/chameleon-base#263 needs to be merged before this.
=> ref #16: fix name of image crop preset after field was made multilingual

src/ShopPaymentTransactionBundle/exceptions/TPkgShopPaymentTransactionException_PaymentHandlerDoesNotSupportTransaction.class.php
| Fixed issues  | chameleon-system/chameleon-system#497
=> ref #497: Correct exception type for orderStatusAddedHook

src/ShopBundle/Basket/BasketVariableReplacer.php, src/ShopBundle/Bridge/Chameleon/Migration/Script/update-1588073204.inc.php, src/ShopBundle/Resources/config/services.xml, src/ShopBundle/Resources/views/snippets/ShopBundle/BasketForm/hiddenBasketFields.html.twig, src/ShopBundle/mappers/basket/TPkgShopMapper_ArticleAddToBasket.class.php
To avoid caching of those parameters we add them in a post process step
| BC breaks?    | maybe, but not critical. See below.
| Fixed issues  | chameleon-system/chameleon-system#582
Currently all request parameters are added as hidden fields to add-to-basket forms. When enabling cache, those parameters will be part of the created cache. To avoid this, there is a new post processing step, that will replace the placeholder `[{BASKETHIDDENFIELDS}]` in the HTML with hidden fields of all request parameters. This way, only the placeholder will be cached and replaced with the current values on every call.
Existing systems …
=> Use placeholder to set hidden basket button fields

src/ShopBundle/objects/TShopBasket/TShopBasketCore.class.php, src/ShopBundle/objects/TShopBasket/TShopBasketVoucherCoreList.class.php
Fix #540
| Branch        | 6.2.x 
| Tests pass?   | yes   
The voucher list now holds an internal state to avoid double checking already checked and valid vouchers. This is not the prettiest fix but we need to hold this state internally as some code assumes the list to be the same as the active list in the current basket. That's the reason why the last fix crashed the system under certain circumstances. While the idea to use different voucher lists for the different types of vouchers was good, the implementation of some validation checks conflicted with this idea. So the new …
=> Add internal state for voucher list

src/ShopBundle/objects/TShopBasket/TShopBasketCore.class.php, src/ShopBundle/objects/TShopBasket/TShopBasketVoucherCoreList.class.php
| BC breaks?    | no 
Yet another approach at finally fixing the recalculation of the vouchers. In this approach we no longer remember already valid vouchers, but instead set the type that is currently being calculated and skip all vouchers that are not of that type.
We need to set the type in the basket because we cannot alter signature of the method to provide it with an optional filter since this would introduce a bc break.
=> set active voucher type to filter inside the list

src/ShopBundle/objects/db/TShopPaymentHandler/TShopPaymentHandlerPayPal_PayViaLink.class.php
| Fixed issues  | chameleon-system/chameleon-system#588
TShopPaymentHandlerPayPal_PayViaLink::getLogger replaced with ::getPayPalLogger()
=> ref:588 getPayPalLogger used as LoggerService

src/ShopBundle/objects/db/TShopPaymentHandler/TShopPaymentHandlerPayPal_PayViaLink.class.php
the method used to send data to paypal already returns only the body of the response.
| Fixed issues  | chameleon-system/chameleon-system#613
Error was introduced when removing deprecated code - hence the fix is only for 7.0.x
=> ref #613: fix paypal ipn handling

src/ShopBundle/Basket/BasketVariableReplacer.php, src/ShopBundle/Resources/views/snippets/ShopBundle/BasketForm/hiddenBasketFields.html.twig
| BC breaks?    | no 
| Fixed issues  | chameleon-system/chameleon-system#622
In case of an error rendering a parameter, this error will be logged and the parameter will be skipped. This prevents the process to give up entirely on error and to not replace the placeholder at all.
=> 622: skip params that cannot be rendered

src/ShopBundle/Basket/BasketVariableReplacer.php, src/ShopBundle/Resources/config/services.xml, src/ShopBundle/Resources/views/snippets/ShopBundle/BasketForm/hiddenBasketFields.html.twig
| BC breaks?    | no   
| Tests pass?   | yes   
| Fixed issues  | chameleon-system/chameleon-system#629
The replacer now uses the new pre-output-event to only replace the basket variables if there is a need to do so.
=> 629 only collect parameters when necessary

src/ShopBundle/Bridge/Chameleon/Migration/Script/update-1604649540.inc.php, src/ShopBundle/objects/WebModules/MTShopBasketCore/MTShopBasketCoreEndpoint.class.php
Together chameleon-system/chameleon-shop-theme-bundle#38 this fixes chameleon-system/chameleon-system#654
| Fixed issues  | chameleon-system/chameleon-system#654
This PR adds the `basketUrl` post render variable for usage in the mini shop basket templates in order to
prevent caching of the 'continue shopping' URL.
=> Add basketUrl post render variable

src/ShopListFilterBundle/objects/db/ListfilterItems/TPkgShopListfilterItemMultiselectMLT.class.php
| Fixed issues  | chameleon-system/chameleon-system#685
- aActiveFilterData validation via is_array extended.
- $aValues inline-variable removed.
=> 685 multiselect listfilter search problem

src/ShopRatingServiceBundle/objects/TShopAuskunftAPI.class.php
| Branch        | 7.1
| Deprecations? | yes 
| Fixed issues  | chameleon-system/chameleon-system#652   
Replaces all deprecated named constructors with __construct using the backwards compatibility shim introduced in chameleon-system/chameleon-base#525 .
chameleon-system/chameleon-base#525 must be merged before merging this PR.
=> ref #652:  Replace named constructors with __construct

src/ShopListFilterBundle/mappers/filter/TPkgShopListfilterMapper_FilterNumericSlider.class.php
| Fixed issues  | chameleon-system/chameleon-system#398
Test case (resolved):
1. Go to the demo shop.
2. Navigate via the menu "Art Prints" / "Chameleon Prints", you can see now a list of products and a price filter sidebar.
3. Deactivate some products (like "Chameleon on the finger") in the CMS until you have a product's price range between 30 € and 39 € (for example).
- The price filter range should now a range between 30 and 39 and is changeable in 1 € steps.
- Also the jQuery / Javascript error in the browser's developer console should not visible no more.
- If the difference of the min …
=> 46264 increase filter resolution

src/ShopListFilterBundle/mappers/filter/TPkgShopListfilterMapper_FilterNumericSlider.class.php
| Fixed issues  | chameleon-system/chameleon-system#398
Test case:
(See last issue description) Change product price range from 11€ to 39€ e.g., so the price filter value range is between 10 and 30 (instead 39).
=> re #46264: Fix round value bug

src/ShopRatingServiceBundle/objects/TShopAuskunftAPI.class.php
| Fixed issues  | chameleon-system/chameleon-system#725  
Replaces a usage of the `each` function which was removed in PHP8 with it's `foreach` equivalent.
=> ref #725: Replace `each` function usage with `foreach`

.github/workflows/ci.yaml, composer.json
| Fixed issues  | chameleon-system/chameleon-system#770  
Adds a workflow for running psalm & phpunit in github actions. A branch for 7.1.x also exists - I'll open a PR for it once #121 has been merged.
=> 770 GitHub actions

src/ShopBundle/Service/ShopService.php
| Fixed issues  | 
\ChameleonSystem\ShopBundle\Service\ShopService::getActiveProduct
did not check for existing requestStack like other methods in this class already do.
now it will and resulting errors prior to fix won't occur anymore.
=> fix active product retrieval if no request stack available

src/ShopBundle/objects/WebModules/MTShopPageMetaCore/MTShopPageMetaCore.class.php
| Fixed issues  | chameleon-system/chameleon-system#810
=> 810 canonical url on product list pages contains empty listpage parameter

src/SearchBundle/objects/db/TShopSearchIndexer.class.php
| Branch        | 7.0.x for bug fixes
| Tests pass?   | no
| Fixed issues  | chameleon-system/chameleon-system#825
This commit fixes the exception error after a table row for the search index tables was added about a year ago (@see #117).
The corresponding sql query for custom keywords has to be the same structure and column row count as the queries for the index tables, thus a missing row was also added (just a dummy value).
Note: If an article does not be shown - but without an error - then the chosen connected article is not flagged as a "Mabuse article" - so it is not an error at all.
Technical said, the condition is …
=> ref #825: add id field for table structure like search index tables
